[build]
  # Command to build the Angular app
  command = "npm run build"
  # Folder where the compiled static files go (default for ng build)
  publish = "dist/didkobravo/browser"

[[redirects]]
  # This is crucial for Angular routing (so URLs like /systems work)
  from = "/*"
  to = "/index.html"
  status = 200